### ISSUE TITLE
"is_solved": false on all results

### ISSUE THREAD

**Issue by drammen94** [noahshinn024/reflexion#2]
Do we need to adjust some parameters or anything? i tried running both run_reflexion.sh and run_simple.sh but all of the tests fail.

**Comment by noahshinn024** [comment]
> Do we need to adjust some parameters or anything? i tried running both run_reflexion.sh and run_simple.sh but all of the tests fail.

Thanks for the note. Can you specify the run parameters that you used? Also, check the latest rewrite. It may make it easier to interpret results now.

**Comment by drammen94** [comment]
Hi Noah! Im running the default parameter except im using 3.5 turbo. It appears to fault under execution.

I tried running on jupyter lab to debug further

![image](https://user-images.githubusercontent.com/18756107/228385277-8a9d7bc9-d932-4dc6-9f99-ecce0fd1d9ea.png)

It says attribute error.
Although the code passes when i paste it in jupyter lab.

![image](https://user-images.githubusercontent.com/18756107/228385597-6e68fbd1-4e47-4eee-8a4b-f896bb01e945.png)
